<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>New Html</title>
</head>

<body>
    <script>
        /*
            Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。
        */
        const jqueryAjax = function (type, url, data = {}) {
            return new Promise(function (resolve, reject) {
                $.ajax({
                    url,
                    data,
                    type,
                    success (data) {
                        resolve(data);
                    },
                    error: err => {
                        reject(err);
                    }
                })
            })
        }

        // 写一个箭头函数
        const fn = () => console.log("1");
        const fn1 = () => {
            console.log("2");
        }

        // 添加
        // jqueryAjax("POST", "/add", { useranme }).then(function (data) {
        //     console.log(data);
        // }, function (err) {
        //     console.log(err);
        // })
        jqueryAjax("POST", "/add", { useranme }).then((data, data1) => {
            console.log(data);
        }, err => {
            console.log(err);
        })
        // 渲染
        jqueryAjax("GET", "/list").then(function (data) {
            console.log(data);
        }, function (err) {
            console.log(err);
        })

        /*
            then(f,f)
                promise成功时执行第一个回调函数
                promise失败时执行第二个回调函数
            catch(f)
                promise失败时执行catch()方法
            两个失败同时存在执行的区别:同时存在只执行then的第二个回调函数

        */

    </script>
</body>

</html>